---
title: Завершение ошибки | Документация Майкрософт
ms.custom: ''
ms.date: 09/13/2016
ms.reviewer: ''
ms.suite: ''
ms.tgt_pltfrm: ''
ms.topic: article
ms.assetid: b804e738-aefa-41bb-9649-f9ed897fd96c
caps.latest.revision: 8
ms.openlocfilehash: d1967fe7996f75ec5229920f7ec49aa5ff6bdbfd
ms.sourcegitcommit: e7445ba8203da304286c591ff513900ad1c244a4
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/23/2019
ms.locfileid: "62067388"
---
# <a name="terminating-errors"></a><span data-ttu-id="70697-102">Прерывающие ошибки</span><span class="sxs-lookup"><span data-stu-id="70697-102">Terminating Errors</span></span>

<span data-ttu-id="70697-103">В этом разделе рассматривается метод, используемый для отчетов, завершение ошибки.</span><span class="sxs-lookup"><span data-stu-id="70697-103">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="70697-104">Также описывается вызов метода в командлет, и в нем рассматриваются исключения, которые могут быть возвращены средой выполнения Windows PowerShell, при вызове метода.</span><span class="sxs-lookup"><span data-stu-id="70697-104">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="70697-105">При прекращении возникает ошибка, командлет должен сообщить об ошибке, вызвав [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) метод.</span><span class="sxs-lookup"><span data-stu-id="70697-105">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="70697-106">Этот метод позволяет командлету отправлять запись об ошибке, которое описывает условие, вызвавшее Неустранимая ошибка.</span><span class="sxs-lookup"><span data-stu-id="70697-106">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="70697-107">Дополнительные сведения о записи об ошибках, см. в разделе [записи об ошибках Windows PowerShell](./windows-powershell-error-records.md).</span><span class="sxs-lookup"><span data-stu-id="70697-107">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="70697-108">Когда [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) вызывается метод, среда выполнения Windows PowerShell останавливает выполнение конвейера и без возможности восстановления создает [ System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) исключение.</span><span class="sxs-lookup"><span data-stu-id="70697-108">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="70697-109">Все последующие попытки вызова [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), или несколько других интерфейсов API вызывает исключение вызовы[ System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) исключение.</span><span class="sxs-lookup"><span data-stu-id="70697-109">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="70697-110">[System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) исключение также может возникнуть, если другому командлету в конвейере выдает неустранимую ошибку, если пользователь запросил остановить конвейера или конвейер остановлен до завершения по любой причине.</span><span class="sxs-lookup"><span data-stu-id="70697-110">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="70697-111">Командлет не требуется перехватывать [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) исключение, если необходимо открыть очистку ресурсов или внутреннего состояния.</span><span class="sxs-lookup"><span data-stu-id="70697-111">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="70697-112">Командлеты можно создать любое количество выходных объектов или устранимые ошибки до появления неустранимую ошибку.</span><span class="sxs-lookup"><span data-stu-id="70697-112">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="70697-113">Тем не менее Неустранимая ошибка без возможности восстановления останавливается конвейера, а не Дополнительные выходные данные, завершение ошибки, или устранимые ошибки может быть включено в отчет.</span><span class="sxs-lookup"><span data-stu-id="70697-113">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="70697-114">Командлеты можно вызвать [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) только из потока, который вызвал [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [ System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), или [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) метод обработки ввода.</span><span class="sxs-lookup"><span data-stu-id="70697-114">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="70697-115">Не пытайтесь вызвать [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) или [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) из другого потока.</span><span class="sxs-lookup"><span data-stu-id="70697-115">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="70697-116">Вместо этого ошибки необходимо передать обратно в основной поток.</span><span class="sxs-lookup"><span data-stu-id="70697-116">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="70697-117">Это возможно для командлета, для создания исключения в своей реализации [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), или [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) метод.</span><span class="sxs-lookup"><span data-stu-id="70697-117">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="70697-118">Любое исключение, возникшее из этих методов (за исключением нескольких серьезные ошибки, которые остановить узел Windows PowerShell) интерпретируется как неустранимую ошибку, которая останавливает конвейера, но не в Windows PowerShell в целом.</span><span class="sxs-lookup"><span data-stu-id="70697-118">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="70697-119">(Это относится только к командлет основной поток.</span><span class="sxs-lookup"><span data-stu-id="70697-119">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="70697-120">Неперехваченных исключений в потоков, созданных с помощью командлета в общем случае остановка узлов Windows PowerShell.) Мы рекомендуем использовать [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) вместо создания исключения, так как запись об ошибке дополнительная информация об ошибке, что полезно для конечному пользователю.</span><span class="sxs-lookup"><span data-stu-id="70697-120">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="70697-121">Командлеты должны учитываться в случае управляемого кода, рекомендуется от перехват и обработка всех исключений (`catch (Exception e)`).</span><span class="sxs-lookup"><span data-stu-id="70697-121">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="70697-122">Преобразуйте только исключения известного и ожидаемого типов в записи об ошибках.</span><span class="sxs-lookup"><span data-stu-id="70697-122">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="70697-123">См. также</span><span class="sxs-lookup"><span data-stu-id="70697-123">See Also</span></span>

[<span data-ttu-id="70697-124">System.Management.Automation.Cmdlet.BeginProcessing</span><span class="sxs-lookup"><span data-stu-id="70697-124">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="70697-125">System.Management.Automation.Cmdlet.EndProcessing</span><span class="sxs-lookup"><span data-stu-id="70697-125">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="70697-126">System.Management.Automation.Cmdlet.ProcessRecord</span><span class="sxs-lookup"><span data-stu-id="70697-126">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="70697-127">System.Management.Automation.Pipelinestoppedexception</span><span class="sxs-lookup"><span data-stu-id="70697-127">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="70697-128">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span><span class="sxs-lookup"><span data-stu-id="70697-128">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="70697-129">System.Management.Automation.Cmdlet.WriteError</span><span class="sxs-lookup"><span data-stu-id="70697-129">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="70697-130">Записи об ошибках PowerShell Windows</span><span class="sxs-lookup"><span data-stu-id="70697-130">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="70697-131">Запись командлета Windows PowerShell</span><span class="sxs-lookup"><span data-stu-id="70697-131">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
